// resources/js/components/MyComponent.vue
<template>
    <div class="container">
        <p>{{msg}}</p>
        <hr>
        <input type="text" v-model="name">
        <button v-on:click="doAction">click</button>

        <ul>
            <li v-for="(person,key) in people">
                {{person.id}}: {{person.name}} [{{person.mail}}] ({{person.age}})
            </li>
        </ul>
    </div>
</template>

<script>
    const axios = require('axios');
    export default {
        mounted() {
            axios.get('/hello/json').then(response => {
                console.log(response)
                this.people = response.data;
                this.msg = 'get data!';
            });
        },
        data:function() {
            return {
                msg:'wait...',
                name: '',
                people: [],
            };
        },
        methods: {
            doAction:function() {
                this.msg = 'Hello, ' + this.name + '!!';
            }
        }
    }
</script>

// resources/ngapp/src/app/my/my.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import axios from 'axios';


@Component({
  selector: 'app-my',
  templateUrl: './my.component.html',
  styleUrls: ['./my.component.css']
})
export class MyComponent implements OnInit {

  message: string;
  input: FormControl;

  constructor() { }

  ngOnInit() {
    this.message = 'please input your name:';
    this.input = new FormControl('noname');
  }

  doAction() {
    axios.get('/hello/json/' + this.input.value)
      .then(response =>{
          let person = response.data;
          let msg = person.id + ':' + person.name
              + ' [' + person.mail + '] ('
              + person.age + ')';
          this.message = msg;
      });
  }
}
<div>
    <p>{{message}}</p>
    <input type="number" [formControl]="input" />
    <button (click)="doAction()">click</button>
</div>
